# Runs weekly or after every push to all branches to validate indexing against staging/production environments

trigger:
  branches:
    include: ["main", "*"]
  paths:
    exclude: ["doc", "*.md"]

schedules:
- cron: "0 15 * * Wed" # Wed @ 8 or 9 AM Mountain Time (depending on DST)
  displayName: Weekly Production Environment Validation Run
  branches:
    include:
    - main
  always: true

queue:
  name: Hosted VS2017
  timeoutInMinutes: 60

steps:
- task: MS-RichCodeNav.Indexer.build-task.RichCodeNavIndexer@0
  displayName: Rich Code Navigation Upload to Production
  inputs:
    serviceConnection: 'richCodeNav-Token-Prod'
    languages: 'csharp,typescript,java,cpp'
    githubServiceConnection: 'xuachen'
    environment: production
    richNavLogOutputDirectory: $(Build.SourcesDirectory)/artifacts/bin
  continueOnError: true

