# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core sdk 2.1.300'
  inputs:
    version: 2.1.300

- task: vsintellinav.vsck-service-endpoint.build-task.upload-cache-build-task@0
  displayName: 'VS IntelliNav Upload'
  inputs:
    vsckEndpoint: 'vscloudkernel-dev'
    nugetpat: 'vsck-nuget'
    language: 'typescript;csharp'
    githubpat: 'jumattos (1)'
    nugetVersion: 'latest'