### This template is meant to be used by a TypeScript or JavaScript repository running RichNav
### Please fill anything marked above with a "# **** #" comment with the value appropriate for your repository

name: Rich Code Navigation (Node JS)

on:
  pull_request:
  push:
  # **** Add any the name of your default branch, or any branch you want indexed on every push **** #
    branches: [ main ]

jobs:
  richnav:

    runs-on: windows-latest

    # **** If necessary, use the Node version for your repository. Note: must be greater than 10.x **** #
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: yarn
      working-directory: typescript
    
    - uses: microsoft/RichCodeNavIndexer@v0.1
      with: 
        languages: typescript
        repo-token: ${{ secrets.GITHUB_TOKEN }}
     
